title: Q-SEE SIGD2

date: 2016

7.jpg:
  description: <br>Kim Westfall

8.jpg:
  description: <br>Kim Westfall
  
9.jpg:
  description: <br>Kim Westfall
  
10.jpg:
  description: <br>Jared Brown

11.jpg:
  description: <br>Kim Westfall
  
12.jpg:
  description: <br>Kim Westfall
  
13.jpg:
  description: <br>Kim Westfall
  
14.jpg:
  description: <br>Kim Westfall
  
16.jpg:
  description: <br>Kim Westfall
  
  
content: +++
June 18 - July 9, 2016<br><br><a href="http://doyouknowjaredbrown.com">Jared Brown</a><br><a href="http://westfalleast.tumblr.com">Kim Westfall</a><br><br><a href="http://bb427.tk/files/qseesigd2_text.pdf">Read gallery text</a><br>View "<a href="http://vimeo.com/148897706">His Eye Is On Me</a>" video
(Jared Brown) <br><br>Photography: <a href="http://michaelbussell.com">Michael Bussell</a>
+++
