title: A Temporary Curse

date: 2016

9.jpg:
  description: <br>Stephanie Hier
  
13.jpg:
  description: <br>Michael Bussell
  
15.jpg:
  description: <br>Noa Glazer

19.jpg:
  description: <br>Stephanie Hier

20.jpg:
  description: <br>Michael Bussell

21.jpg:
  description: <br>Noa Glazer

23.jpg:
  description: <br>Michael Bussell

24.jpg:
  description: <br>Stephanie Hier

25.jpg:
  description: <br>Michael Bussell
  
28.jpg:
  description: <br>Michael Bussell

31.jpg:
  description: <br>Noa Glazer
  
content: +++
April 2 - May 21, 2016
<br><br><a href="http://michaelbussell.com">Michael Bussell</a><br><a href="http://cargocollective.com/noaglazer">Noa Glazer</a><br><a href="http://stephaniehier.com">Stephanie Hier</a><br><br><a href="http://bb427.tk/files/atc%20press%20release.pdf">Read gallery text</a>


Photography: <a href="http://michaelbussell.com">Michael Bussell</a>
+++
