title: Brass In Pocket, Third Chorus
date: 2015

0.jpg:
 description: <br> Julia Yerger
2.jpg:
 description: <br> Audrey Gair
5.jpg:
 description: <br> Audrey Gair
2792.jpg:
 description: <br> Julia Yerger
2798.jpg:
 description: <br> Maggie Fitz
2800.jpg:
 description: <br> Max Guy
2804.jpg:
 description: <br> Maggie Fitz
2815.jpg:
 description: <br> Audrey Gair
2861.jpg:
 description: <br> Julia Yerger
"2912 (2).jpg":
 description: <br> Audrey Gair
2922.jpg:
 description: <br> Max Guy
2931.jpg:
 description: <br> Max Guy
2940.jpg:
 description: <br> Max Guy
2943.jpg:
 description: <br> Audrey Gair
2947.jpg:
 description: <br> Audrey Gair
2956.jpg:
 description: <br> Audrey Gair
2979.jpg:
 description: <br> Alex Goss


content: +++

Rm. 109, 7410 Ocean Terrace, Miami Beach, FL
Dec. 1-6, 2015
<br>

<a href="http://www.audreygair.com/">Audrey Gair</a>
<a href="https://www.alexgoss.net/">Alex Goss</a>
<a href="http://www.maximilianguy.com/">Max Guy</a>
<a href="http://www.maggot.website/">Maggie Fitz</a>
<a href="http://jahdonkey.tumblr.com/tagged/my-work">Julia Yerger</a>
<br>
<a href="/files/pdfs/BIP3C.pdf">Read gallery text</a>

+++
