title: Slsleeping
date: 2015
2437.jpg: 
 description: <br>Christina Haines
2445.jpg: 
 description: <br>Grace Davis
2569.jpg: 
 description: <br>Michael Jones McKean
2571.jpg: 
 description: <br>John Zane Zappas
content: +++
Artist-Run Art Fair, 1714 N. Charles Street, Baltimore, MD 21201
July 17-19, 2015
<br>
<a href="http://cargocollective.com/gracedavis">Grace Davis</a>
<a href="http://johnzanezappas.com/">John Zane Zappas</a>
<a href="http://michaeljonesmckean.com">Michael Jones McKean</a>
<a href="http://christinahaines.tictail.com/">Christina Haines</a>

+++
