title: Hello World
date: 2014
content: +++
December 13, 2014
<br>

A one night event that presented two paintings by <a href="https://www.instagram.com/markwehberg/">Mark Wehberg</a> in
the front and the back room, each paired with a drink.

In the storefront space, candles warmly glowed and lit the room from sconces and candlesticks made by the basement studio residents. Two large particle-board tables in half-circles were the serving ground for each drink. For the front room, a loose-leaf pine tea tasted of turpentine; the other drink was a Negroni: 1:1:1 Gin, Campari, and Sweet Vermouth.

In the back space, above a single large bench, a cool blue light illuminated a painting of a moonlit woman.
+++
