title: Femmewrath
date: 2015
content: +++


December 19, 2016
Organized by Marcelline Mandeng<br><br>


<a href="http://trnsgndrvhs.bandcamp.com/">TRNSGNDR/VHS</a><br><a href="https://soundcloud.com/lil-island">Marcelline</a><br>Greydolf<br>Planta<br><a href="http://soundcloud.com/sunatirene">Sunatirene</a><br>Afia Lydia<br>Noelle Tolbert

Video credit: Dennis
+++
